### ISSUE TITLE
No identity-based policy allows the ssm:GetServiceSetting action

### ISSUE THREAD

**Issue by patrickznk** [aws-samples/aws-systems-manager-default-host-management-configuration#1]
Hello there, 

we are facing the follow error, if we deploy the StackSet:

Resource handler returned message: "Resource of type 'AWS::SSM::Association' with identifier '4a65b230-3bb7-4b13-8f16-d97ac1c4e7ea' did not stabilize." (RequestToken: 6b9e0702-5379-664c-f454-f83c72e35757, HandlerErrorCode: NotStabilized)

After further investigation, we found this error in SSM automation:

Failure message
Step fails when it is Execute/Cancelling action. An error occurred (AccessDeniedException) when calling the GetServiceSetting operation: User: arn:aws:sts::210945550679:assumed-role/AutomationServiceRole-EnableDefaultSSM/Automation-52d6bfb4-f932-4d8d-9db3-c49e54b06e06 is not authorized to perform: ssm:GetServiceSetting on resource: arn:aws:ssm:eu-central-1:210945550679:servicesetting/arn:aws:ssm:eu-central-1:210945550679:servicesetting/ssm/managed-instance/default-ec2-instance-management-role because no identity-based policy allows the ssm:GetServiceSetting action. Please refer to Automation Service Troubleshooting Guide for more diagnosis details.

Is anyone else facing this error and unable to deploy the StackSet?

**Comment by patrickznk** [comment]
I fixed the issue with a DependsOn.

`  automationRunbookEnableDefaultSSM:`
`    Type: AWS::SSM::Document`
`    DependsOn: automationServiceRole`

**Comment by skinsman** [comment]
Thanks @patrickznk, I hit the same problem and your fix worked.  However I then hit another "failed to stabilize" issue until I removed "WaitForSuccessTimeoutSeconds: 300" as the AWS::SSM::Association doco says it's no longer supported.

**Comment by awserik** [comment]
Apologies for the delay in responding. It seems I was not receiving notifications for issues. The latest version of the CFN template added a `DependsOn` for the Automation IAM service role and removed the WaitForSuccessTimeoutSeconds parameter so the stack should stabilize during deployment. Please let me know if the issue persists.
