### ISSUE TITLE
Incorrect Samples

### ISSUE THREAD

**Issue by fmardini** [aws-samples/aws-systems-manager-default-host-management-configuration#2]
Hi,

https://github.com/aws-samples/aws-systems-manager-default-host-management-configuration/blob/main/enableDefaultHostManagement.yml#L50

Seems to be buggy (copy paste error?)

Furthermore, the association seems to be missing required fields per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-association.html

Running the above I kept getting errors (unable to stabilize)

**Comment by KittieHearts42** [comment]
I'm getting the same error, any idea of the cause?

**Comment by awserik** [comment]
Apologies for the delay in responding. It seems I was not receiving notifications for issues. The latest version of the CFN template added a `DependsOn` for the Automation IAM service role so the stack should stabilize during deployment. Please let me know if the issue persists.
